### PR TITLE
feat: add first chapter

### PR DESCRIPTION
**Pull request by thielpa**

### CODE REVIEW

**Review by hofbi — CHANGES_REQUESTED** [review]
I prefer not to commit the latex4ei classes, but if you want to do so please use at least latest version https://github.com/latex4ei/latex4ei-packages/releases/latest

**Review by rossmeier — CHANGES_REQUESTED** [review]
[Systemtheorie-korrektur.pdf](https://github.com/latex4ei/Systemtheorie/files/3219481/Systemtheorie-korrektur.pdf)

**Comment by rossmeier** [comment]
[Systemtheorie-korr.pdf.pdf](https://github.com/latex4ei/Systemtheorie/files/3391163/Systemtheorie-korr.pdf.pdf)

**Review by rossmeier — CHANGES_REQUESTED** [review]
[Systemtheorie-korr.pdf](https://github.com/latex4ei/Systemtheorie/files/3394523/Systemtheorie-korr.pdf)

**Comment by TheSerious** [comment]
[Systemtheorie - korrektur.pdf :)](https://github.com/latex4ei/Systemtheorie/files/3418654/Systemtheorie.-.korregur.pdf)

**Comment by thielpa** [comment]
[corr.pdf.pdf](https://github.com/latex4ei/Systemtheorie/files/3422772/corr.pdf.pdf)

**Comment by thielpa** [comment]
Bin an der Jordan-Normalform

**Review by rossmeier — APPROVED** [review]

**Review by hofbi — APPROVED** [review]

**Pull request merged**
